version: "3.9"

services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - my-net
    volumes:
      - mysql-volume:/d/mysql_data
    environment:
      MYSQL_ROOT_PASSWORD: admin123
  zookeeper:
    platform: linux/x86_64
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-net
  kafka:
    platform: linux/x86_64
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    networks:
      - my-net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal # production
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092 # production
  java-api:
    platform: linux/x86_64
    container_name: java-api
    image: java-api:1.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=admin123
    networks:
      - my-net

networks:
  my-net:
    name: my-net

volumes:
  mysql-volume:
    external: true